// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/NoticeModal.tsx": () => import("../components/mockups/NoticeModal.tsx"),
  "./components/mockups/ProfileCardNew.tsx": () => import("../components/mockups/ProfileCardNew.tsx")
};
