const _BASE = import.meta.env.BASE_URL ?? '/';
// DiceBear API로 캐릭터 아바타 생성 (style별 일러스트 자동 생성)
const _db = (style: string, seed: string, bg = 'b6e3f4,c0aede,d1d4f9,ffd5dc,ffdfbf') =>
  `https://api.dicebear.com/9.x/${style}/svg?seed=${encodeURIComponent(seed)}&radius=50&size=100&backgroundColor=${bg}`;
// 이모지 + 배경색 SVG (음식 등 단순 표현용)
const _ea = (e: string, c: string) => {
  const s = `<svg xmlns='http://www.w3.org/2000/svg' width='100' height='100'><circle cx='50' cy='50' r='50' fill='${c}'/><text x='50' y='68' font-size='54' text-anchor='middle'>${e}</text></svg>`;
  return `data:image/svg+xml;charset=utf-8,${encodeURIComponent(s)}`;
};
export const AVATAR_CATEGORIES = [
  // ── 인물 (애니/일러스트) ──────────────────────────────────────────────────
  { label: '✨ 인물', avatars: [
    { id:'av1',  src:`${_BASE}avatars/av1.webp`,  label:'핑크 요정' },
    { id:'av2',  src:`${_BASE}avatars/av2.webp`,  label:'민트 페어리' },
    { id:'av3',  src:`${_BASE}avatars/av3.webp`,  label:'퍼플 쿨가이' },
    { id:'av4',  src:`${_BASE}avatars/av4.webp`,  label:'코럴 큐티' },
    { id:'av5',  src:`${_BASE}avatars/av5.webp`,  label:'다크 시크' },
    { id:'av6',  src:`${_BASE}avatars/av6.webp`,  label:'레인보우' },
    { id:'av7',  src:`${_BASE}avatars/av7.webp`,  label:'베어 후디' },
    { id:'av8',  src:`${_BASE}avatars/av8.webp`,  label:'레트로 팜므' },
    { id:'av9',  src:`${_BASE}avatars/av9.webp`,  label:'스포티 짐' },
    { id:'av10', src:`${_BASE}avatars/av10.webp`, label:'북덕 지성파' },
    { id:'av19', src:`${_BASE}avatars/av19.webp`, label:'별빛 마법사' },
    { id:'av20', src:`${_BASE}avatars/av20.webp`, label:'닌자 소년' },
    { id:'av21', src:`${_BASE}avatars/av21.webp`, label:'실버 미남' },
    { id:'av22', src:`${_BASE}avatars/av22.webp`, label:'다크 귀족' },
    { id:'av23', src:`${_BASE}avatars/av23.webp`, label:'스포츠 에이스' },
    { id:'av24', src:`${_BASE}avatars/av24.webp`, label:'블루 스타' },
    { id:'av25', src:`${_BASE}avatars/av25.webp`, label:'도서관 지성' },
    { id:'av26', src:`${_BASE}avatars/av26.webp`, label:'다크 마법사' },
    { id:'av27', src:`${_BASE}avatars/av27.webp`, label:'불꽃 전사' },
    { id:'av28', src:`${_BASE}avatars/av28.webp`, label:'썬샤인 보이' },
    { id:'av29', src:`${_BASE}avatars/av29.webp`, label:'어쿠스틱 가이' },
    { id:'av30', src:`${_BASE}avatars/av30.webp`, label:'코지 스웨터' },
    { id:'av31', src:`${_BASE}avatars/av31.webp`, label:'배틀 파이터' },
    { id:'av32', src:`${_BASE}avatars/av32.webp`, label:'신비 엘프' },
    { id:'av33', src:`${_BASE}avatars/av33.webp`, label:'파스텔 레인보우' },
    { id:'av34', src:`${_BASE}avatars/av34.webp`, label:'냥코 큐티' },
    { id:'av35', src:`${_BASE}avatars/av35.webp`, label:'다크 앤젤' },
    { id:'av36', src:`${_BASE}avatars/av36.webp`, label:'오렌지 트윈테일' },
    { id:'av37', src:`${_BASE}avatars/av37.webp`, label:'사무라이' },
    { id:'av38', src:`${_BASE}avatars/av38.webp`, label:'숲의 요정' },
  ]},
  // ── 케이팝/현실 ────────────────────────────────────────────────────────────
  { label: '🎤 케이팝/현실', avatars: [
    { id:'av39', src:`${_BASE}avatars/av39.webp`, label:'케이팝 아이돌' },
    { id:'av40', src:`${_BASE}avatars/av40.webp`, label:'도심 보이' },
    { id:'av41', src:`${_BASE}avatars/av41.webp`, label:'서울 래퍼' },
    { id:'av42', src:`${_BASE}avatars/av42.webp`, label:'핑크 걸' },
    { id:'av43', src:`${_BASE}avatars/av43.webp`, label:'Y2K 버터플라이' },
    { id:'av44', src:`${_BASE}avatars/av44.webp`, label:'블랙 수트' },
    { id:'av45', src:`${_BASE}avatars/av45.webp`, label:'하늘 스마일' },
    { id:'av46', src:`${_BASE}avatars/av46.webp`, label:'보라 아이돌' },
    { id:'av47', src:`${_BASE}avatars/av47.webp`, label:'그래피티 가이' },
    { id:'av48', src:`${_BASE}avatars/av48.webp`, label:'벚꽃 러브' },
    { id:'av118',src:`${_BASE}avatars/av118.webp`,label:'걸그룹 댄서' },
    { id:'av119',src:`${_BASE}avatars/av119.webp`,label:'스트리트 패션' },
    { id:'av120',src:`${_BASE}avatars/av120.webp`,label:'시티팝 가수' },
    { id:'av121',src:`${_BASE}avatars/av121.webp`,label:'DJ 걸' },
    { id:'av122',src:`${_BASE}avatars/av122.webp`,label:'교복 K-pop' },
    { id:'av123',src:`${_BASE}avatars/av123.webp`,label:'스포티 보이' },
    { id:'av124',src:`${_BASE}avatars/av124.webp`,label:'발라드 가수' },
    { id:'av125',src:`${_BASE}avatars/av125.webp`,label:'빈티지 힙합' },
    { id:'av126',src:`${_BASE}avatars/av126.webp`,label:'보이그룹 비주얼' },
    { id:'av127',src:`${_BASE}avatars/av127.webp`,label:'솔로 아티스트' },
    { id:'av128',src:`${_BASE}avatars/av128.webp`,label:'재즈 뮤지션' },
    { id:'av129',src:`${_BASE}avatars/av129.webp`,label:'배틀 댄서' },
    { id:'av130',src:`${_BASE}avatars/av130.webp`,label:'K-드라마 히어로' },
    { id:'av131',src:`${_BASE}avatars/av131.webp`,label:'인디 기타리스트' },
    { id:'av132',src:`${_BASE}avatars/av132.webp`,label:'MV 여주' },
  ]},
  // ── 퀴어/프라이드 ──────────────────────────────────────────────────────────
  { label: '🏳️‍🌈 퀴어/프라이드', avatars: [
    { id:'av49', src:`${_BASE}avatars/av49.webp`, label:'레인보우 프라이드' },
    { id:'av50', src:`${_BASE}avatars/av50.webp`, label:'드래그 퀸' },
    { id:'av51', src:`${_BASE}avatars/av51.webp`, label:'젠더플루이드' },
    { id:'av52', src:`${_BASE}avatars/av52.webp`, label:'논바이너리' },
    { id:'av53', src:`${_BASE}avatars/av53.webp`, label:'트랜스 프라이드' },
    { id:'av54', src:`${_BASE}avatars/av54.webp`, label:'레즈비언 프라이드' },
    { id:'av55', src:`${_BASE}avatars/av55.webp`, label:'게이 프라이드' },
    { id:'av56', src:`${_BASE}avatars/av56.webp`, label:'퀴어 액티비스트' },
  ]},
  // ── 판타지/어드벤처 ────────────────────────────────────────────────────────
  { label: '⚔️ 판타지/어드벤처', avatars: [
    { id:'av57', src:`${_BASE}avatars/av57.webp`, label:'엘프 아처' },
    { id:'av58', src:`${_BASE}avatars/av58.webp`, label:'다크 워리어' },
    { id:'av59', src:`${_BASE}avatars/av59.webp`, label:'갤럭시 마법사' },
    { id:'av60', src:`${_BASE}avatars/av60.webp`, label:'사이버펑크' },
    { id:'av61', src:`${_BASE}avatars/av61.webp`, label:'뱀파이어 공작' },
    { id:'av62', src:`${_BASE}avatars/av62.webp`, label:'별빛 마녀' },
    { id:'av63', src:`${_BASE}avatars/av63.webp`, label:'우주 탐험가' },
    { id:'av64', src:`${_BASE}avatars/av64.webp`, label:'황금 전사' },
    { id:'av65', src:`${_BASE}avatars/av65.webp`, label:'빛의 천사' },
    { id:'av66', src:`${_BASE}avatars/av66.webp`, label:'미지의 모험가' },
    { id:'av67', src:`${_BASE}avatars/av67.webp`, label:'달빛 마법사' },
    { id:'av68', src:`${_BASE}avatars/av68.webp`, label:'드래곤 기사' },
    { id:'av69', src:`${_BASE}avatars/av69.webp`, label:'신비로운 자' },
    { id:'av70', src:`${_BASE}avatars/av70.webp`, label:'섀도우 닌자' },
    { id:'av71', src:`${_BASE}avatars/av71.webp`, label:'불꽃 기사' },
    { id:'av72', src:`${_BASE}avatars/av72.webp`, label:'얼음 마법사' },
    { id:'av73', src:`${_BASE}avatars/av73.webp`, label:'하늘 전사' },
    { id:'av74', src:`${_BASE}avatars/av74.webp`, label:'숲속 레인저' },
    { id:'av75', src:`${_BASE}avatars/av75.webp`, label:'인디 록' },
    { id:'av76', src:`${_BASE}avatars/av76.webp`, label:'어반 아티스트' },
    { id:'av77', src:`${_BASE}avatars/av77.webp`, label:'밤의 기사' },
    { id:'av78', src:`${_BASE}avatars/av78.webp`, label:'고독한 검사' },
    { id:'av79', src:`${_BASE}avatars/av79.webp`, label:'바람의 정령' },
    { id:'av80', src:`${_BASE}avatars/av80.webp`, label:'카페 바리스타' },
    { id:'av81', src:`${_BASE}avatars/av81.webp`, label:'도시 탐험가' },
    { id:'av82', src:`${_BASE}avatars/av82.webp`, label:'현대 전사' },
    { id:'av83', src:`${_BASE}avatars/av83.webp`, label:'낙원의 수호자' },
    { id:'av84', src:`${_BASE}avatars/av84.webp`, label:'미래 여전사' },
    { id:'av85', src:`${_BASE}avatars/av85.webp`, label:'세계 여행자' },
    { id:'av86', src:`${_BASE}avatars/av86.webp`, label:'야생 탐험가' },
    { id:'av87', src:`${_BASE}avatars/av87.webp`, label:'바다 모험가' },
    { id:'av88', src:`${_BASE}avatars/av88.webp`, label:'클래식 학자' },
    { id:'av89', src:`${_BASE}avatars/av89.webp`, label:'숲의 수호자' },
  ]},
  // ── 동물 ──────────────────────────────────────────────────────────────────
  { label: '🐾 동물', avatars: [
    { id:'av15', src:`${_BASE}avatars/av15.webp`, label:'시바 이누' },
    { id:'av16', src:`${_BASE}avatars/av16.webp`, label:'드리미 냥' },
    { id:'av17', src:`${_BASE}avatars/av17.webp`, label:'프라이드 펭귄' },
    { id:'av18', src:`${_BASE}avatars/av18.webp`, label:'선셋 여우' },
    { id:'av90', src:`${_BASE}avatars/av90.webp`, label:'판다' },
    { id:'av178',src:`${_BASE}avatars/av178.webp`,label:'하얀 토끼' },
    { id:'av179',src:`${_BASE}avatars/av179.webp`,label:'골든 리트리버' },
    { id:'av180',src:`${_BASE}avatars/av180.webp`,label:'페르시안 고양이' },
    { id:'av181',src:`${_BASE}avatars/av181.webp`,label:'햄스터' },
    { id:'av182',src:`${_BASE}avatars/av182.webp`,label:'다람쥐' },
    { id:'av183',src:`${_BASE}avatars/av183.webp`,label:'부엉이' },
    { id:'av184',src:`${_BASE}avatars/av184.webp`,label:'고슴도치' },
    { id:'av185',src:`${_BASE}avatars/av185.webp`,label:'아기 악어' },
    { id:'av186',src:`${_BASE}avatars/av186.webp`,label:'코알라' },
    { id:'av187',src:`${_BASE}avatars/av187.webp`,label:'미어캣' },
    { id:'av188',src:`${_BASE}avatars/av188.webp`,label:'너구리' },
    { id:'av189',src:`${_BASE}avatars/av189.webp`,label:'알파카' },
    { id:'av190',src:`${_BASE}avatars/av190.webp`,label:'개구리' },
    { id:'av191',src:`${_BASE}avatars/av191.webp`,label:'비글' },
    { id:'av192',src:`${_BASE}avatars/av192.webp`,label:'아기 공룡' },
    { id:'av220',src:`${_BASE}avatars/av220.webp`,label:'불곰' },
    { id:'av221',src:`${_BASE}avatars/av221.webp`,label:'호랑이' },
    { id:'av222',src:`${_BASE}avatars/av222.webp`,label:'사자' },
    { id:'av223',src:`${_BASE}avatars/av223.webp`,label:'기린' },
    { id:'av224',src:`${_BASE}avatars/av224.webp`,label:'코끼리' },
    { id:'av225',src:`${_BASE}avatars/av225.webp`,label:'얼룩말' },
    { id:'av226',src:`${_BASE}avatars/av226.webp`,label:'분홍 돼지' },
    { id:'av227',src:`${_BASE}avatars/av227.webp`,label:'양' },
    { id:'av228',src:`${_BASE}avatars/av228.webp`,label:'젖소' },
    { id:'av229',src:`${_BASE}avatars/av229.webp`,label:'말' },
    { id:'av230',src:`${_BASE}avatars/av230.webp`,label:'오리' },
    { id:'av231',src:`${_BASE}avatars/av231.webp`,label:'병아리' },
    { id:'av232',src:`${_BASE}avatars/av232.webp`,label:'앵무새' },
    { id:'av233',src:`${_BASE}avatars/av233.webp`,label:'플라밍고' },
    { id:'av234',src:`${_BASE}avatars/av234.webp`,label:'오리너구리' },
    { id:'av235',src:`${_BASE}avatars/av235.webp`,label:'아기 바다표범' },
    { id:'av236',src:`${_BASE}avatars/av236.webp`,label:'고래' },
    { id:'av237',src:`${_BASE}avatars/av237.webp`,label:'돌고래' },
    { id:'av238',src:`${_BASE}avatars/av238.webp`,label:'아기 상어' },
    { id:'av239',src:`${_BASE}avatars/av239.webp`,label:'바다거북' },
    { id:'av240',src:`${_BASE}avatars/av240.webp`,label:'오징어' },
    { id:'av241',src:`${_BASE}avatars/av241.webp`,label:'문어' },
    { id:'av242',src:`${_BASE}avatars/av242.webp`,label:'카피바라' },
    { id:'av243',src:`${_BASE}avatars/av243.webp`,label:'수달' },
    { id:'av244',src:`${_BASE}avatars/av244.webp`,label:'비버' },
    { id:'av245',src:`${_BASE}avatars/av245.webp`,label:'고릴라' },
    { id:'av246',src:`${_BASE}avatars/av246.webp`,label:'여우원숭이' },
    { id:'av247',src:`${_BASE}avatars/av247.webp`,label:'카멜레온' },
    { id:'av248',src:`${_BASE}avatars/av248.webp`,label:'낙타' },
    { id:'av249',src:`${_BASE}avatars/av249.webp`,label:'두더지' },
  ]},
  // ── 음식 (식사류) ──────────────────────────────────────────────────────────
  { label: '🍱 음식', avatars: [
    { id:'av11', src:`${_BASE}avatars/av11.webp`, label:'라멘' },
    { id:'av99', src:`${_BASE}avatars/av99.webp`, label:'라멘 군' },
    { id:'av101',src:`${_BASE}avatars/av101.webp`,label:'타코야키' },
    { id:'av193',src:`${_BASE}avatars/av193.webp`,label:'순두부찌개' },
    { id:'av194',src:`${_BASE}avatars/av194.webp`,label:'스시' },
    { id:'av195',src:`${_BASE}avatars/av195.webp`,label:'카레라이스' },
    { id:'av196',src:`${_BASE}avatars/av196.webp`,label:'피자' },
    { id:'av197',src:`${_BASE}avatars/av197.webp`,label:'햄버거' },
    { id:'av198',src:`${_BASE}avatars/av198.webp`,label:'마라탕' },
    { id:'av199',src:`${_BASE}avatars/av199.webp`,label:'아이스 아메리카노' },
    { id:'av200',src:`${_BASE}avatars/av200.webp`,label:'떡볶이' },
    { id:'av201',src:`${_BASE}avatars/av201.webp`,label:'삼겹살' },
    { id:'av202',src:`${_BASE}avatars/av202.webp`,label:'후라이드 치킨' },
    { id:'av203',src:`${_BASE}avatars/av203.webp`,label:'비빔밥' },
    { id:'av204',src:`${_BASE}avatars/av204.webp`,label:'파스타' },
    { id:'av205',src:`${_BASE}avatars/av205.webp`,label:'샌드위치' },
    { id:'av206',src:`${_BASE}avatars/av206.webp`,label:'핫도그' },
    { id:'av207',src:`${_BASE}avatars/av207.webp`,label:'쌀국수' },
    { id:'av250',src:`${_BASE}avatars/av250.webp`,label:'김밥' },
    { id:'av251',src:`${_BASE}avatars/av251.webp`,label:'된장찌개' },
    { id:'av252',src:`${_BASE}avatars/av252.webp`,label:'짜장면' },
    { id:'av253',src:`${_BASE}avatars/av253.webp`,label:'짬뽕' },
    { id:'av254',src:`${_BASE}avatars/av254.webp`,label:'닭갈비' },
    { id:'av255',src:`${_BASE}avatars/av255.webp`,label:'갈비탕' },
    { id:'av256',src:`${_BASE}avatars/av256.webp`,label:'칼국수' },
    { id:'av257',src:`${_BASE}avatars/av257.webp`,label:'오므라이스' },
    { id:'av258',src:`${_BASE}avatars/av258.webp`,label:'타코' },
    { id:'av259',src:`${_BASE}avatars/av259.webp`,label:'팟타이' },
    { id:'av260',src:`${_BASE}avatars/av260.webp`,label:'규동' },
    { id:'av261',src:`${_BASE}avatars/av261.webp`,label:'오코노미야키' },
    { id:'av262',src:`${_BASE}avatars/av262.webp`,label:'부대찌개' },
    { id:'av263',src:`${_BASE}avatars/av263.webp`,label:'잡채' },
    { id:'av264',src:`${_BASE}avatars/av264.webp`,label:'갈비찜' },
    { id:'av265',src:`${_BASE}avatars/av265.webp`,label:'새우 튀김' },
    { id:'av266',src:`${_BASE}avatars/av266.webp`,label:'연어 스테이크' },
    { id:'av267',src:`${_BASE}avatars/av267.webp`,label:'리조또' },
    { id:'av268',src:`${_BASE}avatars/av268.webp`,label:'포케볼' },
    { id:'av269',src:`${_BASE}avatars/av269.webp`,label:'팔라펠' },
    { id:'av270',src:`${_BASE}avatars/av270.webp`,label:'크루아상' },
    { id:'av271',src:`${_BASE}avatars/av271.webp`,label:'베이글' },
    { id:'av272',src:`${_BASE}avatars/av272.webp`,label:'클램차우더' },
    { id:'av273',src:`${_BASE}avatars/av273.webp`,label:'그릭 요거트' },
    { id:'av274',src:`${_BASE}avatars/av274.webp`,label:'콩나물국밥' },
    { id:'av275',src:`${_BASE}avatars/av275.webp`,label:'나시고랭' },
    { id:'av276',src:`${_BASE}avatars/av276.webp`,label:'월남쌈' },
    { id:'av277',src:`${_BASE}avatars/av277.webp`,label:'시저 샐러드' },
    { id:'av278',src:`${_BASE}avatars/av278.webp`,label:'뇨키' },
    { id:'av279',src:`${_BASE}avatars/av279.webp`,label:'새우 파스타' },
    { id:'av280',src:`${_BASE}avatars/av280.webp`,label:'연어 덮밥' },
    { id:'av281',src:`${_BASE}avatars/av281.webp`,label:'냉면' },
  ]},
  // ── 디저트 ────────────────────────────────────────────────────────────────
  { label: '🧁 디저트', avatars: [
    { id:'av12', src:`${_BASE}avatars/av12.webp`, label:'마카롱' },
    { id:'av14', src:`${_BASE}avatars/av14.webp`, label:'버블티' },
    { id:'av98', src:`${_BASE}avatars/av98.webp`, label:'딸기 케이크' },
    { id:'av100',src:`${_BASE}avatars/av100.webp`,label:'버블티 짱' },
    { id:'av102',src:`${_BASE}avatars/av102.webp`,label:'소금빵' },
    { id:'av103',src:`${_BASE}avatars/av103.webp`,label:'탕후루' },
    { id:'av104',src:`${_BASE}avatars/av104.webp`,label:'도넛' },
    { id:'av105',src:`${_BASE}avatars/av105.webp`,label:'에그타르트' },
    { id:'av208',src:`${_BASE}avatars/av208.webp`,label:'크레페' },
    { id:'av209',src:`${_BASE}avatars/av209.webp`,label:'아이스크림 콘' },
    { id:'av210',src:`${_BASE}avatars/av210.webp`,label:'쿠키' },
    { id:'av211',src:`${_BASE}avatars/av211.webp`,label:'초콜릿 케이크' },
    { id:'av212',src:`${_BASE}avatars/av212.webp`,label:'와플' },
    { id:'av213',src:`${_BASE}avatars/av213.webp`,label:'구미 베어' },
    { id:'av214',src:`${_BASE}avatars/av214.webp`,label:'대만 카스텔라' },
    { id:'av215',src:`${_BASE}avatars/av215.webp`,label:'붕어빵' },
    { id:'av216',src:`${_BASE}avatars/av216.webp`,label:'크로플' },
    { id:'av217',src:`${_BASE}avatars/av217.webp`,label:'마카롱 타워' },
    { id:'av218',src:`${_BASE}avatars/av218.webp`,label:'솜사탕' },
    { id:'av219',src:`${_BASE}avatars/av219.webp`,label:'화이트 초코 퐁듀' },
    { id:'av282',src:`${_BASE}avatars/av282.webp`,label:'과일 타르트' },
    { id:'av283',src:`${_BASE}avatars/av283.webp`,label:'티라미수' },
    { id:'av284',src:`${_BASE}avatars/av284.webp`,label:'치즈케이크' },
    { id:'av285',src:`${_BASE}avatars/av285.webp`,label:'밀레 크레페' },
    { id:'av286',src:`${_BASE}avatars/av286.webp`,label:'쇼트케이크' },
    { id:'av287',src:`${_BASE}avatars/av287.webp`,label:'타로 밀크티' },
    { id:'av288',src:`${_BASE}avatars/av288.webp`,label:'모나카' },
    { id:'av289',src:`${_BASE}avatars/av289.webp`,label:'팥빙수' },
    { id:'av290',src:`${_BASE}avatars/av290.webp`,label:'캐러멜 푸딩' },
    { id:'av291',src:`${_BASE}avatars/av291.webp`,label:'판나코타' },
    { id:'av292',src:`${_BASE}avatars/av292.webp`,label:'브라우니' },
    { id:'av293',src:`${_BASE}avatars/av293.webp`,label:'롤케이크' },
    { id:'av294',src:`${_BASE}avatars/av294.webp`,label:'에클레어' },
    { id:'av295',src:`${_BASE}avatars/av295.webp`,label:'프렌치 토스트' },
    { id:'av296',src:`${_BASE}avatars/av296.webp`,label:'슈크림' },
    { id:'av297',src:`${_BASE}avatars/av297.webp`,label:'딸기 파르페' },
    { id:'av298',src:`${_BASE}avatars/av298.webp`,label:'소프트 아이스크림' },
    { id:'av299',src:`${_BASE}avatars/av299.webp`,label:'초콜릿 트러플' },
    { id:'av300',src:`${_BASE}avatars/av300.webp`,label:'호두과자' },
    { id:'av301',src:`${_BASE}avatars/av301.webp`,label:'찹쌀떡' },
    { id:'av302',src:`${_BASE}avatars/av302.webp`,label:'약과' },
    { id:'av303',src:`${_BASE}avatars/av303.webp`,label:'식혜' },
    { id:'av304',src:`${_BASE}avatars/av304.webp`,label:'흑임자 라떼' },
    { id:'av305',src:`${_BASE}avatars/av305.webp`,label:'말차 케이크' },
    { id:'av306',src:`${_BASE}avatars/av306.webp`,label:'레인보우 케이크' },
    { id:'av307',src:`${_BASE}avatars/av307.webp`,label:'마들렌' },
    { id:'av308',src:`${_BASE}avatars/av308.webp`,label:'츄러스' },
    { id:'av309',src:`${_BASE}avatars/av309.webp`,label:'레몬 타르트' },
    { id:'av310',src:`${_BASE}avatars/av310.webp`,label:'다이후쿠 모찌' },
    { id:'av311',src:`${_BASE}avatars/av311.webp`,label:'까눌레' },
  ]},
  // ── 일상 소품 ──────────────────────────────────────────────────────────────
  { label: '📷 일상 소품', avatars: [
    { id:'av106',src:`${_BASE}avatars/av106.webp`,label:'카세트 테이프' },
    { id:'av107',src:`${_BASE}avatars/av107.webp`,label:'폴라로이드' },
    { id:'av108',src:`${_BASE}avatars/av108.webp`,label:'스마일 플라워' },
    { id:'av109',src:`${_BASE}avatars/av109.webp`,label:'헤드폰 텀블러' },
    { id:'av133',src:`${_BASE}avatars/av133.webp`,label:'스케이트보드' },
    { id:'av134',src:`${_BASE}avatars/av134.webp`,label:'테니스 라켓' },
    { id:'av135',src:`${_BASE}avatars/av135.webp`,label:'야구 글러브' },
    { id:'av136',src:`${_BASE}avatars/av136.webp`,label:'향수병' },
    { id:'av137',src:`${_BASE}avatars/av137.webp`,label:'책갈피' },
    { id:'av138',src:`${_BASE}avatars/av138.webp`,label:'핀 버튼 배지' },
    { id:'av139',src:`${_BASE}avatars/av139.webp`,label:'에코백' },
    { id:'av140',src:`${_BASE}avatars/av140.webp`,label:'양초' },
    { id:'av141',src:`${_BASE}avatars/av141.webp`,label:'스노우 글로브' },
    { id:'av142',src:`${_BASE}avatars/av142.webp`,label:'열기구' },
    { id:'av143',src:`${_BASE}avatars/av143.webp`,label:'레인부츠' },
    { id:'av144',src:`${_BASE}avatars/av144.webp`,label:'엽서' },
    { id:'av145',src:`${_BASE}avatars/av145.webp`,label:'선인장' },
    { id:'av146',src:`${_BASE}avatars/av146.webp`,label:'무지개 연' },
    { id:'av147',src:`${_BASE}avatars/av147.webp`,label:'개구리 우산' },
  ]},
  // ── 판타지/우주 ────────────────────────────────────────────────────────────
  { label: '🌙 판타지/우주', avatars: [
    { id:'av110',src:`${_BASE}avatars/av110.webp`,label:'마법 포션' },
    { id:'av111',src:`${_BASE}avatars/av111.webp`,label:'스마일 유령' },
    { id:'av112',src:`${_BASE}avatars/av112.webp`,label:'구름 위 별' },
    { id:'av113',src:`${_BASE}avatars/av113.webp`,label:'윙크 초승달' },
    { id:'av114',src:`${_BASE}avatars/av114.webp`,label:'몽글 우주인' },
    { id:'av148',src:`${_BASE}avatars/av148.webp`,label:'별똥별' },
    { id:'av149',src:`${_BASE}avatars/av149.webp`,label:'토성' },
    { id:'av150',src:`${_BASE}avatars/av150.webp`,label:'파스텔 아기 용' },
    { id:'av151',src:`${_BASE}avatars/av151.webp`,label:'수정 구슬' },
    { id:'av152',src:`${_BASE}avatars/av152.webp`,label:'요정 날개' },
    { id:'av153',src:`${_BASE}avatars/av153.webp`,label:'마법 지팡이' },
    { id:'av154',src:`${_BASE}avatars/av154.webp`,label:'마법의 책' },
    { id:'av155',src:`${_BASE}avatars/av155.webp`,label:'반딧불이' },
    { id:'av156',src:`${_BASE}avatars/av156.webp`,label:'마법 왕관' },
    { id:'av157',src:`${_BASE}avatars/av157.webp`,label:'무지개' },
    { id:'av158',src:`${_BASE}avatars/av158.webp`,label:'수호 정령' },
    { id:'av159',src:`${_BASE}avatars/av159.webp`,label:'새싹 요정' },
    { id:'av160',src:`${_BASE}avatars/av160.webp`,label:'마법 불꽃' },
    { id:'av161',src:`${_BASE}avatars/av161.webp`,label:'크리스탈' },
    { id:'av162',src:`${_BASE}avatars/av162.webp`,label:'별자리 지도' },
  ]},
  // ── 무기물 캐릭터 ──────────────────────────────────────────────────────────
  { label: '🖥️ 무기물', avatars: [
    { id:'av115',src:`${_BASE}avatars/av115.webp`,label:'레트로 컴퓨터' },
    { id:'av116',src:`${_BASE}avatars/av116.webp`,label:'픽셀 게임기' },
    { id:'av117',src:`${_BASE}avatars/av117.webp`,label:'빈티지 시계' },
    { id:'av163',src:`${_BASE}avatars/av163.webp`,label:'레코드 플레이어' },
    { id:'av164',src:`${_BASE}avatars/av164.webp`,label:'타자기' },
    { id:'av165',src:`${_BASE}avatars/av165.webp`,label:'그랜드 피아노' },
    { id:'av166',src:`${_BASE}avatars/av166.webp`,label:'바이올린' },
    { id:'av167',src:`${_BASE}avatars/av167.webp`,label:'어쿠스틱 기타' },
    { id:'av168',src:`${_BASE}avatars/av168.webp`,label:'빈티지 라디오' },
    { id:'av169',src:`${_BASE}avatars/av169.webp`,label:'구형 TV' },
    { id:'av170',src:`${_BASE}avatars/av170.webp`,label:'다이얼 전화기' },
    { id:'av171',src:`${_BASE}avatars/av171.webp`,label:'우편함' },
    { id:'av172',src:`${_BASE}avatars/av172.webp`,label:'책상 램프' },
    { id:'av173',src:`${_BASE}avatars/av173.webp`,label:'오르골' },
    { id:'av174',src:`${_BASE}avatars/av174.webp`,label:'우표' },
    { id:'av175',src:`${_BASE}avatars/av175.webp`,label:'노란 잠수함' },
    { id:'av176',src:`${_BASE}avatars/av176.webp`,label:'레트로 로봇' },
    { id:'av177',src:`${_BASE}avatars/av177.webp`,label:'필름 카메라' },
  ]},
  // ── 과일 ──────────────────────────────────────────────────────────────────
  { label: '🍓 과일', avatars: [
    { id:'av13', src:`${_BASE}avatars/av13.webp`, label:'아보카도' },
    { id:'av312',src:`${_BASE}avatars/av312.webp`,label:'딸기' },
    { id:'av313',src:`${_BASE}avatars/av313.webp`,label:'사과' },
    { id:'av314',src:`${_BASE}avatars/av314.webp`,label:'바나나' },
    { id:'av315',src:`${_BASE}avatars/av315.webp`,label:'포도' },
    { id:'av316',src:`${_BASE}avatars/av316.webp`,label:'오렌지' },
    { id:'av317',src:`${_BASE}avatars/av317.webp`,label:'수박' },
    { id:'av318',src:`${_BASE}avatars/av318.webp`,label:'복숭아' },
    { id:'av319',src:`${_BASE}avatars/av319.webp`,label:'망고' },
    { id:'av320',src:`${_BASE}avatars/av320.webp`,label:'파인애플' },
    { id:'av321',src:`${_BASE}avatars/av321.webp`,label:'체리' },
    { id:'av322',src:`${_BASE}avatars/av322.webp`,label:'블루베리' },
    { id:'av323',src:`${_BASE}avatars/av323.webp`,label:'레몬' },
    { id:'av324',src:`${_BASE}avatars/av324.webp`,label:'라임' },
    { id:'av325',src:`${_BASE}avatars/av325.webp`,label:'키위' },
    { id:'av326',src:`${_BASE}avatars/av326.webp`,label:'파파야' },
    { id:'av327',src:`${_BASE}avatars/av327.webp`,label:'용과' },
    { id:'av328',src:`${_BASE}avatars/av328.webp`,label:'리치' },
    { id:'av329',src:`${_BASE}avatars/av329.webp`,label:'패션후르츠' },
    { id:'av330',src:`${_BASE}avatars/av330.webp`,label:'구아바' },
    { id:'av331',src:`${_BASE}avatars/av331.webp`,label:'귤' },
    { id:'av332',src:`${_BASE}avatars/av332.webp`,label:'자몽' },
    { id:'av333',src:`${_BASE}avatars/av333.webp`,label:'배' },
    { id:'av334',src:`${_BASE}avatars/av334.webp`,label:'멜론' },
    { id:'av335',src:`${_BASE}avatars/av335.webp`,label:'자두' },
    { id:'av336',src:`${_BASE}avatars/av336.webp`,label:'살구' },
    { id:'av337',src:`${_BASE}avatars/av337.webp`,label:'유자' },
    { id:'av338',src:`${_BASE}avatars/av338.webp`,label:'석류' },
    { id:'av339',src:`${_BASE}avatars/av339.webp`,label:'무화과' },
    { id:'av340',src:`${_BASE}avatars/av340.webp`,label:'감' },
    { id:'av341',src:`${_BASE}avatars/av341.webp`,label:'대추' },
    { id:'av342',src:`${_BASE}avatars/av342.webp`,label:'금귤' },
    { id:'av343',src:`${_BASE}avatars/av343.webp`,label:'천도복숭아' },
    { id:'av344',src:`${_BASE}avatars/av344.webp`,label:'산딸기' },
    { id:'av345',src:`${_BASE}avatars/av345.webp`,label:'블랙베리' },
    { id:'av346',src:`${_BASE}avatars/av346.webp`,label:'크랜베리' },
    { id:'av347',src:`${_BASE}avatars/av347.webp`,label:'오디' },
    { id:'av348',src:`${_BASE}avatars/av348.webp`,label:'두리안' },
    { id:'av349',src:`${_BASE}avatars/av349.webp`,label:'람부탄' },
    { id:'av350',src:`${_BASE}avatars/av350.webp`,label:'스타프루트' },
    { id:'av351',src:`${_BASE}avatars/av351.webp`,label:'코코넛' },
    { id:'av352',src:`${_BASE}avatars/av352.webp`,label:'포멜로' },
    { id:'av353',src:`${_BASE}avatars/av353.webp`,label:'아사이베리' },
    { id:'av354',src:`${_BASE}avatars/av354.webp`,label:'참외' },
    { id:'av355',src:`${_BASE}avatars/av355.webp`,label:'매실' },
    { id:'av356',src:`${_BASE}avatars/av356.webp`,label:'앵두' },
    { id:'av357',src:`${_BASE}avatars/av357.webp`,label:'청사과' },
    { id:'av358',src:`${_BASE}avatars/av358.webp`,label:'흰 딸기' },
    { id:'av359',src:`${_BASE}avatars/av359.webp`,label:'청포도' },
    { id:'av360',src:`${_BASE}avatars/av360.webp`,label:'클레멘타인' },
  ]},
];

/** All preset ids — keep in sync with api-server avatar-preset-ids.json */
export const AVATAR_PRESET_IDS = AVATAR_CATEGORIES.flatMap((c) => c.avatars.map((a) => a.id));

export function presetAvatarSrc(id: string): string {
  return `${_BASE}avatars/${id}.webp`;
}
